// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreatePostInput struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorID string `json:"authorID"`
}

type CreateUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type DeletePostInput struct {
	ID string `json:"id" bson:"_id"`
}

type DeleteUserInput struct {
	ID string `json:"id" bson:"_id"`
}

type Post struct {
	ID      string `json:"id" bson:"_id"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  *User  `json:"author"`
}

type UpdatePostInput struct {
	ID      string  `json:"id" bson:"_id"`
	Title   *string `json:"title"`
	Content *string `json:"content"`
}

type UpdateUserInput struct {
	ID       string  `json:"id" bson:"_id"`
	Name     *string `json:"name"`
	Email    *string `json:"email"`
	Password string  `json:"password"`
}

type User struct {
	ID       string  `json:"id" bson:"_id"`
	Name     string  `json:"name"`
	Email    string  `json:"email"`
	Posts    []*Post `json:"posts"`
	Password string  `json:"password"`
}
